const PDFDocument = require("pdfkit");

//utils/Export/pdfExport.js
// ======================================================
// EXPORT PDF
// ======================================================

exports.exportToPDF = async ({
  res,
  title = "Report",
  columns = [],
  rows = [],
}) => {

  const doc = new PDFDocument({
    margin: 40,
    size: "A4",
  });

  res.setHeader(
    "Content-Type",
    "application/pdf"
  );

  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${title}.pdf`
  );

  doc.pipe(res);

  // ======================
  // TITLE
  // ======================

  doc
    .fontSize(22)
    .text(title, {
      align: "center",
    });

  doc.moveDown();

  doc
    .fontSize(10)
    .text(
      `Generated : ${new Date().toLocaleString()}`
    );

  doc.moveDown();

  // ======================
  // HEADER
  // ======================

  doc.font("Helvetica-Bold");

  columns.forEach((column) => {

    doc.text(column.header, {
      continued: true,
      width: 100,
    });

  });

  doc.moveDown();

  doc.font("Helvetica");

  // ======================
  // DATA
  // ======================

  rows.forEach((row) => {

    columns.forEach((column) => {

      doc.text(
        String(row[column.key] ?? ""),
        {
          continued: true,
          width: 100,
        }
      );

    });

    doc.moveDown();

  });

  // ======================
  // FOOTER
  // ======================

  doc.moveDown();

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      "Generated by Mantar E-commerce Reporting System",
      {
        align: "center",
      }
    );

  doc.end();

};