name: Mantra CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
        NODE_ENV: test
        MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test --if-present

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-next-app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Next App
        run: npm run build

  deploy:
    needs:
      - backend
      - frontend

    runs-on: ubuntu-latest

    # Pull Request par deploy mat karo
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy Backend to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Deploy Frontend to Vercel
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
